### PR TITLE
Updating dependencies for PHP 8.3 support

### PR DESCRIPTION
**Pull request by snake14**
### Description:

We've been waiting for Google to release an update for PHP 8.3 support. This updates our dependencies to include that update and a few others.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by snake14** [comment]
The failing UI test cases are due to the core navigation shadow change and we're waiting for a long term fix before we update the screenshots. So, I think that we're good to merge once the changes are reviewed/approved.

**Review by AltamashShaikh — COMMENTED** [review]
@snake14 I checked the code for PHP 8.3 and the error goes away for GA plugin, but I am still seeing an error for SearchEngineKeyword plugin, which shouldn't be the case at all as we are prefixing the vendor libraries

Screenshot from 2024-01-17 08-59-04

**Comment by snake14** [comment]
@AltamashShaikh I wasn't able to reproduce that issue with the SEKP warnings, but I did fix the issue with the dynamic property warnings from PHP 8.3. It was an issue with the transpiling process removing the `#[\AllowDynamicProperties]` attribute from some of the Google classes.

**Comment by AltamashShaikh** [comment]
> @AltamashShaikh I wasn't able to reproduce that issue with the SEKP warnings, but I did fix the issue with the dynamic property warnings from PHP 8.3. It was an issue with the transpiling process removing the `#[\AllowDynamicProperties]` attribute from some of the Google classes.

@snake14 I can confirm the error goes away :+1:

**Review by AltamashShaikh — APPROVED** [review]

**Pull request merged**
