### PR TITLE
Replace Travis.CI tests with GitHub action

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

Please include a description of this change and which issue it fixes. If no issue exists yet please include context and what problem it solves.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by AltamashShaikh** [comment]
@sgiehl Its missing the environment variable like we have added here - https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/blob/4.x-dev/.travis.yml#L34

**Comment by sgiehl** [comment]
@AltamashShaikh Is there a specific reason why you introduced a new env variable for that?
We already had `SystemTestCase::isTravisCI` to check if tests are running on travis? This will still work for GitHub to check if tests are running on the CI. 
*Note: For Matomo 5 we will rename that method to `SystemTestCase::isCIEnvironment`*

**Comment by AltamashShaikh** [comment]
> @AltamashShaikh Is there a specific reason why you introduced a new env variable for that? We already had `SystemTestCase::isTravisCI` to check if tests are running on travis? This will still work for GitHub to check if tests are running on the CI. _Note: For Matomo 5 we will rename that method to `SystemTestCase::isCIEnvironment`_

@sgiehl  We have 2 cases
1. To use the mock response 
2. To capture the response by running the APIs and capturing the response under a log file and testing using the generated response which we call mock response and hence we have used it specifically to distinguish both the case

**Comment by sgiehl** [comment]
@AltamashShaikh I've pushed some adjustments, so the tests are using the env `CI` instead (which is set on github). Would that work for you?
I've also fixed the checkout for dependent plugins in the action. Some tests are already working. Feel free to fix the remaining ones ;-)

**Review by snake14 — APPROVED** [review]
Looks good :+1:

**Pull request merged**
