### PR TITLE
Upgraded google api client version to 2.11

### PR DESCRIPTION
**Pull request by AltamashShaikh**
### Description:

Upgraded google api client version to 2.11.
Issue: #DEV-2409

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by tsteur** [comment]
@AltamashShaikh @sgiehl be great to document internally how to update the dependencies in this plugin and search engines and if there is anything to consider like updating both the same version etc.

**Comment by AltamashShaikh** [comment]
> @AltamashShaikh @sgiehl be great to document internally how to update the dependencies in this plugin and search engines and if there is anything to consider like updating both the same version etc.

I have created 1 wiki page internally mentioning, how to update this

**Comment by tsteur** [comment]
@AltamashShaikh there now seems to be this test failing: https://builds-artifacts.matomo.org/matomo-org/plugin-GoogleAnalyticsImporter/4.x-dev/377/GoogleAnalyticsImporter_errored_import.png

It's expecting an error but the UI doesn't show an error?

**Comment by AltamashShaikh** [comment]
> @AltamashShaikh there now seems to be this test failing: https://builds-artifacts.matomo.org/matomo-org/plugin-GoogleAnalyticsImporter/4.x-dev/377/GoogleAnalyticsImporter_errored_import.png
> 
> It's expecting an error but the UI doesn't show an error?

@tsteur 
This test case is failing in 4.x branch too without any upgrade changes

Here only weblate changes were merged still that UI test case failed
https://app.travis-ci.com/github/matomo-org/plugin-GoogleAnalyticsImporter/builds/242269518

Should we remove this UI test ?

**Comment by tsteur** [comment]
Let's keep the test and look into it some day. All good to merge in that case

**Review by sgiehl — APPROVED** [review]
I had a look through the code changes. And from that perspective it should be good to merge. I'm not that much into the functionality of this plugin, so I wasn't able to run the tests and my local testing was rather minimal.

**Pull request merged**
