### PR TITLE
Adjustments according to new no data page layout

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

refs https://github.com/matomo-org/matomo/pull/21247

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by snake14 — APPROVED** [review]
Looks good :+1: 
The only issue I noticed during my testing is that the Cloud specific version of the GA no-data tab has some potential CSS/layout regressions. We likely won't know for sure until we have a Cloud branch with the core no-data changes.

**Comment by sgiehl** [comment]
@snake14 I've increased the required Matomo version to 5.0.0-rc5 (which will be released soon) and updated the test files. I will merge it, would be good if you could release a new version, so the plugin is compatible with last rc.

**Comment by snake14** [comment]
> @snake14 I've increased the required Matomo version to 5.0.0-rc5 (which will be released soon) and updated the test files. I will merge it, would be good if you could release a new version, so the plugin is compatible with last rc.

Thank you @sgiehl . Would it be better to release now or wait till RC5 is released? I can see arguments for both ways. If we release ahead of time, customers might upgrade the plugin before upgrading core. If we release after RC5 is released, then there might be a gap between them upgrading core and the new plugin release becoming available. Of course, there aren't many customers using the RC releases, so it probably doesn't matter much.

**Comment by sgiehl** [comment]
They shouldn't be able to update until rc5 was released. So should be safe to release already.

**Pull request merged**
