### PR TITLE
Added test for phpcs

### PR DESCRIPTION
**Pull request by AltamashShaikh**
### Description:

Added test for phpcs

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by sgiehl** [comment]
@AltamashShaikh I guess it should be better to have a separate action for this. The test yml file can be auto generated with a command. Doing that would throw away the PHPCS part.
Also using strict PSR12 won't easily work without introducing braking changes. This is the CS we are currently using for core: https://github.com/matomo-org/matomo/blob/5.x-dev/phpcs.xml
Note: We are currently working on enabling a few more rules to get closer to PSR12... At some point we need to create a new repository that holds our PHPCS rules, and maybe even allows to add custom rules in the future. Every repo would than need to require those rules and simply run PHPCS with them.

**Comment by AltamashShaikh** [comment]
> @AltamashShaikh I guess it should be better to have a separate action for this. The test yml file can be auto generated with a command. Doing that would throw away the PHPCS part. Also using strict PSR12 won't easily work without introducing braking changes. This is the CS we are currently using for core: https://github.com/matomo-org/matomo/blob/5.x-dev/phpcs.xml Note: We are currently working on enabling a few more rules to get closer to PSR12... At some point we need to create a new repository that holds our PHPCS rules, and maybe even allows to add custom rules in the future. Every repo would than need to require those rules and simply run PHPCS with them.

@sgiehl Yes will move to a separate action and as suggested will make the related changes

**Comment by michalkleiner** [comment]
I would exclude `vendor` and all the prefixed dependencies from the code check, and only apply the action to actual plugin code.
As mentioned before in a meeting, and as Stefan also suggests, longterm we should aim at having something like `matomo-org/matomo-coding-standards` repo that can be shared across core and plugins and cover other areas like JSLint or prettier rules etc., not just PHP. It's a start here though.
Github actions can also be reused from other repo, so here we could simply reference the core repo action (check examples in https://docs.github.com/en/actions/using-workflows/reusing-workflows, mainly https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow).

**Comment by AltamashShaikh** [comment]
> e reused from other repo, so here we could simply reference the core repo action (

@michalkleiner I can try your suggestions and update you accordingly :+1:

**Comment by AltamashShaikh** [comment]
Closing this in favor of #547

**Pull request closed without merging**
