### PR TITLE
Updating tests to validate against PHP version 8.1

### PR DESCRIPTION
**Pull request by snake14**
### Description:

As customers are starting to use PHP version 8.1, we need to make sure that our plugins work as expected with that version. This updates the build to test version 8.1.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by AltamashShaikh — APPROVED** [review]
@snake14 nothing wrong in the approach if its working, can you just remove the commented lines from the code?

**Comment by snake14** [comment]
> @snake14 nothing wrong in the approach if its working, can you just remove the commented lines from the code?

Thank you @AltamashShaikh . With my change, I was able to get all of the builds passing except for the UI tests. I removed the commented line of code as requested.

**Comment by AltamashShaikh** [comment]
> > @snake14 nothing wrong in the approach if its working, can you just remove the commented lines from the code?
> 
> Thank you @AltamashShaikh . With my change, I was able to get all of the builds passing except for the UI tests. I removed the commented line of code as requested.

@snake14 good to merge if test cases are passing

**Comment by snake14** [comment]
> @snake14 good to merge if test cases are passing

Thank you @AltamashShaikh . I think that there are some UI tests that were already failing, but I'm not sure if I'm going to have time to fix them this sprint.

**Comment by snake14** [comment]
Oops. Sorry about requesting review again @AltamashShaikh . I'll just merge this if everything passes except for the UI tests.

**Review by AltamashShaikh — APPROVED** [review]

**Pull request merged**
