### PR TITLE
Abort on all errors and report when when it is due to a insufficient privileges exception.

### LINKED ISSUE #113: Error: Request had insufficient authentication scopes
When running `googleanalyticsimporter:import-reports --idsite=X`

Not sure if this error is somehow avoidable @diosmosis ? Eg when configuring an account can we check needed permissions are there?

Saw this error in the logs:

```
Error: {"message":"{\n \"error\": {\n \"code\": 403,\n \"message\": \"Request had insufficient authentication scopes.\",\n \"errors\": [\n {\n \"message\": \"Insufficient Permission\",\n \"domain\": \"global\",\n \"reason\": \"insufficientPermissions\"\n }\n ],\n \"status\": \"PERMISSION_DENIED\"\n }\n}\n","file":"\/plugins\/GoogleAnalyticsImporter\/vendor\/google\/apiclient\/src\/Google\/Http\/REST.php","line":118,"backtrace":" on \/plugins\/GoogleAnalyticsImporter\/vendor\/google\/apiclient\/src\/Google\/Http\/REST.php(118)\n#0 \/plugins\/GoogleAnalyticsImporter\/vendor\/google\/apiclient\/src\/Google\/Http\/REST.php(94): Google_Http_REST::decodeHttpResponse(Object(GuzzleHttp\\Psr7\\Response), Object(GuzzleHttp\\Psr7\\Request), 'Google_Service_...')\n#1 \/plugins\/GoogleAnalyticsImporter\/vendor\/google\/apiclient\/src\/Google\/Task\/Runner.php(176): Google_Http_REST::doExecute(Object(GuzzleHttp\\Client), Object(GuzzleHttp\\Psr7\\Request), 'Google_Service_...')\n#2 \/plugins\/GoogleAnalyticsImporter\/vendor\/google\/apiclient\/src\/Google\/Http\/REST.php(58): Google_Task_Runner->run()\n#3 \/plugins\/GoogleAnalyticsImporter\/vendor\/google\/apiclient\/src\/Google\/Client.php(862): Google_Http_REST::execute(Object(GuzzleHttp\\Client), Object(GuzzleHttp\\Psr7\\Request), 'Google_Service_...', Array, NULL)\n#4 \/plugins\/GoogleAnalyticsImporter\/vendor\/google\/apiclient\/src\/Google\/Service\/Resource.php(232): Google_Client->execute(Object(GuzzleHttp\\Psr7\\Request), 'Google_Service_...')\n#5 \/plugins\/GoogleAnalyticsImporter\/vendor\/google\/apiclient-services\/src\/Google\/Service\/Analytics\/Resource\/ManagementGoals.php(84): Google_Service_Resource->call('list', Array, 'Google_Service_...')\n#6 \/plugins\/GoogleAnalyticsImporter\/Importer.php(213): Google_Service_Analytics_Resource_ManagementGoals->listManagementGoals('YYYYYYY', 'UA-XXXXXXXX-X', 'XXXXXX')\n#7 \/plugins\/GoogleAnalyticsImporter\/Importer.php(194): Piwik\\Plugins\\GoogleAnalyticsImporter\\Importer->importGoals('2', 'YYYYYYY', 'UA-XXXXXXXX-X', 'XXXX')\n#8 \/plugins\/GoogleAnalyticsImporter\/Commands\/ImportReports.php(174): Piwik\\Plugins\\GoogleAnalyticsImporter\\Importer->importEntities('2', 'YYYYYYY', 'UA-XXXXXXXX-X', 'XXXXXX')\n#9 \/vendor\/symfony\/console\/Symfony\/Component\/Console\/Command\/Command.php(257): Piwik\\Plugins\\GoogleAnalyticsImporter\\Commands\\ImportReports->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#10 \/vendor\/symfony\/console\/Symfony\/Component\/Console\/Application.php(874): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#11 \/vendor\/symfony\/console\/Symfony\/Component\/Console\/Application.php(195): Symfony\\Component\\Console\\Application->doRunCommand(Object(Piwik\\Plugins\\GoogleAnalyticsImporter\\Commands\\ImportReports), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#12 [internal function]: Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#13 \/core\/Console.php(140): call_user_func(Array, Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#14 \/core\/Access.php(644): Piwik\\Console->Piwik\\{closure}()\n#15 \/core\/Console.php(141): Piwik\\Access::doAsSuperUser(Object(Closure))\n#16 \/core\/Console.php(93): Piwik\\Console->doRunImpl(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#17 \/vendor\/symfony\/console\/Symfony\/Component\/Console\/Application.php(126): Piwik\\Console->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#18 \/console(32): Symfony\\Component\\Console\\Application->run()\n#19 {main}"}
```

### PR DESCRIPTION
**Pull request by diosmosis**
Fixes #113 

FYI @tsteur now will not throw an exception on any error, will only report via the UI.

### CODE REVIEW

**Comment by tsteur** [comment]
Thanks @diosmosis

**Comment by tsteur** [comment]
@diosmosis we're still seeing this error I'm not sure if it worked 100%. 

> Error: {"message":"{\n \"error\": {\n \"code\": 403,\n \"message\": \"Request had insufficient authentication scopes.\",\n \"errors\": [\n {\n \"message\": \"Insufficient Permission\",\n \"domain\": \"global\",\n \"reason\": \"insufficientPermissions\"\n }\n ],\n \"status\": \"PERMISSION_DENIED\"\n }\n}\n","file":"\/var\/www\/html\/plugins\/GoogleAnalyticsImporter\/vendor\/google\/apiclient\/src\/Google\/Http\/REST.php","line":118,"backtrace":" on \/var\/www\/html\/plugins\/GoogleAnalyticsImporter\/vendor\/google\/apiclient\/src\/Google\/Http\/REST.php(118)\n#0 \/var\/www\/html\/plugins\/GoogleAnalyticsImporter\/vendor\/google\/apiclient\/src\/Google\/Http\/REST.php(94): Google_Http_REST::decodeHttpResponse(Object(GuzzleHttp\\Psr7\\Response), Object(GuzzleHttp\\Psr7\\Request), 'Google_Service_...')\n#1

Can you maybe quickly check if you can think of anything why it wouldn't work? I'll otherwise need to do a proper deploy to make sure the patch was applied correctly.

**Comment by diosmosis** [comment]
@tsteur it shouldn't rethrow the exception anymore... Unless for some reason the exception doesn't implement Throwable? There's some debugging code left in by accident, but otherwise it should definitely not re-throw any exception now...

**Comment by tsteur** [comment]
OK thanks. Just double checking. Are we sure the exception has code 403 in https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/pull/122/files#diff-e164beaca2661f30d95f51d8865295ffR644 ? It seems to be part of the JSON that you are encoding.  Maybe the check for error 403 isn't needed? If it helps I might just remove it and see if it works then.

**Comment by diosmosis** [comment]
It should have 403, other exceptions have the HTTP code as the Exception code (it's checked for in the GoogleAnalyticsQueryService class). Even if not, ALL errors are ignored now (logged and shown in the UI, but not thrown), so it shouldn't propagate.

**Comment by tsteur** [comment]
OK thanks I'll have an eye on it. For some reason we're still getting those mails hourly. I'll keep you updated.

**Comment by tsteur** [comment]
@diosmosis this is still happening even when I remove the code check. Does it maybe need to be `$messageContent['message']['error']['message']`?

**Comment by tsteur** [comment]
I'll try to apply the patch using the additional `message` key.

**Comment by tsteur** [comment]
@diosmosis I think the problem is actually that it's currently catching exceptions around custom dimensions but currently it is thrown around "importing goals"

> \/var\/www\/html\/plugins\/GoogleAnalyticsImporter\/vendor\/google\/apiclient-services\/src\/Google\/Service\/Analytics\/Resource\/ManagementGoals.php(84): Google_Service_Resource->call('list', Array, 'Google_Service_...')\n#6 \/var\/www\/html\/plugins\/GoogleAnalyticsImporter\/Importer.php(214): Google_Service_Analytics_Resource_ManagementGoals->listManagementGoals('78690943', 'UA-78690943-2', '213039560')\n#7 \/var\/www\/html\/plugins\/GoogleAnalyticsImporter\/Importer.php(195): Piwik\\Plugins\\GoogleAnalyticsImporter\\Importer->importGoals

**Comment by diosmosis** [comment]
@tsteur I think the first message key is just from how Cloud sends the exception info.

I'll add the catch to the other code.

**Pull request merged**
