### PR TITLE
[Vue] remove angularjs use from twig templates

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

* Move index.twig contents to two new components, ClientConfig and AdminPage to get rid of angularjs use.
* Remove reference to piwik-field in tooltip content generator.

refs refs https://github.com/matomo-org/matomo/pull/19944

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by AltamashShaikh** [comment]
@diosmosis we have made changes to the twig template for GA4 and changes to support auto auth for cloud customer, can we merge the latest `4.x-dev` branch and post that do a review ?

**Comment by diosmosis** [comment]
@AltamashShaikh merged and fixed the UI tests (the one failure is random). Can you check again?

**Review by AltamashShaikh — APPROVED** [review]
@diosmosis Works as expected :+1: 
The 1 test failing is random and happens with me too..will also make a note to release this once 
Also we should update the plugin.json and mention that we require min `5.0` version in core.

**Comment by AltamashShaikh** [comment]
@diosmosis we can resolve the conflicts and merge this PR right ?

**Comment by diosmosis** [comment]
@AltamashShaikh updated the PR. test failures seem unrelated.

**Comment by AltamashShaikh** [comment]
> @AltamashShaikh updated the PR. test failures seem unrelated.

@diosmosis fixed those testcases and can be merged

**Comment by diosmosis** [comment]
@AltamashShaikh ok, who is in charge of merging PRs for plugin repos? Do you want me to merge it?

**Pull request merged**
