### PR TITLE
Disable re-import date range feature for GA3, #L3-761

### PR DESCRIPTION
**Pull request by AltamashShaikh**
### Description:

Disable re-import date range feature for GA3
Fixes: #L3-761

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by AltamashShaikh** [comment]
@adammaddox @patrickli We should include this too in tomorrow's release.

**Review by patrickli — COMMENTED** [review]
The frontend code change is a bit too much for me to see any changes. Shall we disable the GA3 checkbox in the UI and add a message next to it to explain why? Throwing an exception on submit is not very user friendly.
Or is this just effecting re-import not a fresh new one?

**Comment by AltamashShaikh** [comment]
> The frontend code change is a bit too much for me to see any changes. Shall we disable the GA3 checkbox in the UI and add a message next to it to explain why? Throwing an exception on submit is not very user friendly. Or is this just effecting re-import not a fresh new one?

@patrickli We have that task to deprecate the GA3 Import, currently we are just hiding the re-import ranges option to ensure we don't face more similar issues.

**Review by patrickli — APPROVED** [review]

**Comment by patrickli** [comment]
Make sure this is merged before tomorrow morning NZ time so I can update `matomo-cloud`.

**Review by adamreng — APPROVED** [review]
Not able to test this myself, but I don't see any issues with the changes 👍

**Comment by AltamashShaikh** [comment]
@patrickli A new version of the plugin is released, we can update the same :+1:

**Pull request merged**
