### PR TITLE
Added escapeShellArg for instanceID get

### PR DESCRIPTION
**Pull request by AltamashShaikh**
### Description:

Please include a description of this change and which issue it fixes. If no issue exists yet please include context and what problem it solves.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by tsteur — CHANGES_REQUESTED** [review]
@AltamashShaikh only had a quick look but it may look faulty. see eg https://3v4l.org/AG8SQ

it would add quotes to the path like `archive.1.'foo.3434.srwewew'.log`. Not sure if that causes issues? 

In tests it's best to not write things like `escapeshellarg($instanceId)` but the actual expected value. This way it's easier to see and understand what it actually does and such things we can spot better.

**Comment by AltamashShaikh** [comment]
@tsteur I updated the code to use `escapeshellcmd` which should solve the issue, please check

**Review by tsteur — COMMENTED** [review]
That looks like it'll work 👍 It'll escape `&#;`|*?~<>^()[]{}$\, \x0A and \xFF. ' and "` which we could also remove in core later such characters.

There may be still edge cases where something can come through. [In the doc](https://www.php.net/manual/en/function.escapeshellcmd.php) it says `escapeshellcmd` is supposed to be called on the whole command not just on parts of it but it's likely good enough and once more changes applied to core it's likely fine. It's not really a security issue anyway as it can be only configured via config

**Comment by AltamashShaikh** [comment]
@tsteur Good to merge this PR ?

**Comment by tsteur** [comment]
Yes 👍

**Pull request merged**
