### PR TITLE
Fix search engine mappings

### PR DESCRIPTION
**Pull request by marto55555**
### Description:

This fixes the mappings of Ecosia and Qwant.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by snake14 — APPROVED** [review]
Looks alright to me :+1: 
Any concerns @AltamashShaikh ? It doesn't look like the build failures are related to these changes, but we should probably find out why they're failing.

**Review by AltamashShaikh — APPROVED** [review]

**Comment by AltamashShaikh** [comment]
> Looks alright to me +1 Any concerns @AltamashShaikh ? It doesn't look like the build failures are related to these changes, but we should probably find out why they're failing.

@snake14 It was same for the other [PR](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/actions/runs/5038810147) too, seems like some access issue maybe ?

**Comment by snake14** [comment]
> > Looks alright to me +1 Any concerns @AltamashShaikh ? It doesn't look like the build failures are related to these changes, but we should probably find out why they're failing.
> 
> @snake14 It was same for the other [PR](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/actions/runs/5038810147) too, seems like some access issue maybe ?

Thanks @AltamashShaikh. That's strange. I guess we're good to merge then.

**Comment by snake14** [comment]
Thank you @marto55555 for taking the time to submit this pull request. These changes should be included in the next release of this plugin.

**Pull request merged**
